### ISSUE TITLE
Add Map Chart

### ISSUE THREAD

**Issue by chalalala** [chalalala/admin-template#6]
A Map Chart is used to display the number of users allowed to borrow money corresponding to regions.
Library:
https://www.react-simple-maps.io/examples/map-chart-with-tooltip/
https://github.com/wwayne/react-tooltip

**Comment by chalalala** [comment]
Map Chart: [Tutorial for react-tooltip](https://www.react-simple-maps.io/examples/map-chart-with-tooltip/) 
Other Charts: [Tutorial for react-chartjs-2](https://www.educative.io/edpresso/how-to-use-chartjs-to-create-charts-in-react)

**Comment by PhuongPhg** [comment]
Didn't need to do this anymore :(
